runtime: go113
env_variables:
  DB_USER: "$DB_USER"
  DB_PASS: "$DB_PASS"
  DB_NAME: "$DB_NAME"
  INSTANCE_CONNECTION_NAME: "$INSTANCE_CONNECTION_NAME"
  RAKUTEN_APP_ID: "$RAKUTEN_APP_ID"
  RAKUTEN_BOOK_API_URL: "$RAKUTEN_BOOK_API_URL"
  CLIENT_ORIGIN: "$CLIENT_ORIGIN"



  

