version: "3.8"

services:
  db-dev:
    image: postgres:12.2-alpine
    container_name: "quote-memo-db-dev"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/posgtresql/data 

  db-test:
    image: postgres:12.2-alpine
    container_name: "quote-memo-db-test"
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  api:
    build: .
    container_name: "quote-memo-api" 
    environment:
      APP_ENV: "development"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres" 
      DB_DB: "postgres"
      DB_HOST: "db-dev"
      DB_TABLE: "postgres"
      DB_PORT: "5432"
      CLIENT_ORIGIN: "http://localhost:3000"
    ports:
      - "8080:8080"
    depends_on:
      - db-dev
    volumes:
        - .:/app
    command: air
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge