version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "quote-manager-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/posgtresql/data 
  
  api:
    build: .
    container_name: "quote-manager-api" 
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres" 
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_TABLE: "postgres"
      DB_PORT: "5432"
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
        - .:/app
    command: air
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge