
name: ci-test

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5431:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: replace app.yaml
        run: |
          sed -i -e "s/$DB_USER/${{ secrets.DB_USER }}/g" app.yaml
          sed -i -e "s/$DB_PASS/${{ secrets.DB_PASS }}/g" app.yaml 
          sed -i -e "s/$INSTANCE_CONNECTION_NAME/${{ secrets.INSTANCE_CONNECTION_NAME }}/g" app.yaml
          sed -i -e "s/$DB_NAME/${{ secrets.DB_NAME }}/g" app.yaml
          sed -i -e "s/$RAKUTEN_APP_ID/${{ secrets.RAKUTEN_APP_ID }}/g" app.yaml
          sed -i -e "s/$RAKUTEN_BOOK_API_URL/${{ secrets.RAKUTEN_BOOK_API_URL }}/g" app.yaml

      - name: Deploy an App Engine app
        id: deploy-app
        uses: google-github-actions/deploy-appengine@v0.3.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: app.yaml
          credentials: ${{ secrets.GCP_SA_KEY }}
          version: v1
